---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: web-app
  namespace: default
spec:
  image: <AWS_ACCOUNT>.dkr.ecr.eu-central-1.amazonaws.com/web-app
  interval: 1h
  provider: generic
  secretRef:
    name: regcred
  