---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: web-app
  namespace: default
spec:
  interval: 30m0s
  path: ./infra/web-app/deploy
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: web-app
  targetNamespace: default
  timeout: 3m0s
  wait: true
